### ISSUE TITLE
непривлекательная анимация меню на моб версии

### ISSUE THREAD

**Issue by bringmetheaugust** [VSerj/i-studio#5]
было бы неплохо сделать открытие меню более плавным.
сейчас выглядит очень топорно.
а закрытие оставить таким же быстрым (как и сейчас).

**Comment by VSerj** [comment]
Теперь появление и скрытие меню работает с помощю свойства: **transform: transitionX**, всместо **left**
Добавил TTFunction **easy-in-out**, было **linear**
Пока и так сойдет )

**Comment by bringmetheaugust** [comment]
технологически оно и так работало. проблема в **UI**.
появление меню должно быть более плавным(предполагаю, что `transition-duration: .7s` будет **ок**).
а исчезновение быстрым (как сейчас `.4s`).

**Comment by VSerj** [comment]
Установил `transition-duration: 0.6s`
Я когда-то читал статью о **UX**, что мы заставляем пользователя ждать и  о анимации контента, который появляется сбоку. Скорее этим и руководствовался.

**Comment by bringmetheaugust** [comment]
теперь чётко и приятно для глаз
