### ISSUE TITLE
эстетика кода

### ISSUE THREAD

**Issue by bringmetheaugust** [VSerj/i-studio#7]
https://github.com/VSerj/i-studio/blob/8f4fbef1e7940034dd4163ac59f75b9553c76e96/src/pug/layout/base.pug#L15
вот тут код за руллер прилично вылез и очень неудобно его читать
нужно рефакторить

**Comment by VSerj** [comment]
Пересмотрел весь pug, постарался убрать длинные строки. 'path' в SVG тоже попробовать уместить, например через конкатенацию?

**Comment by bringmetheaugust** [comment]
да, `path` через конкатенацию.

так же посмотри на этот участок кода https://github.com/VSerj/i-studio/blob/fdb06d4616bcb1ba382c813d0f95aa619d0fc660/src/pug/pages/index.pug#L43 .
если здесь можно применить принцип **DRY**, то так же надо рефакторинг

**Comment by VSerj** [comment]
Не получается через конкатенацию.



> да, `path` через конкатенацию.
> 

Попробую вернуть в цикл
> так же посмотри на этот участок кода
> 
> https://github.com/VSerj/i-studio/blob/fdb06d4616bcb1ba382c813d0f95aa619d0fc660/src/pug/pages/index.pug#L43
> 
> .
> если здесь можно применить принцип **DRY**, то так же надо рефакторинг

**Comment by VSerj** [comment]
Сделать конкатенацию получилось.
Отрефакторил участок.
